from models import Source, UseCase


SOURCES = [
    {
        "source_id": "REG-EU-AIACT-001",
        "title": "EU Artificial Intelligence Act",
        "organization": "European Union",
        "source_type": "Law / Regulation",
        "url": "https://eur-lex.europa.eu/eli/reg/2024/1689",
        "topic": "AI Risk Classification",
        "summary": "Establishes risk-based framework for AI systems in the EU. High-risk AI systems require conformity assessment, transparency, and human oversight.",
        "publication_date": "2024-03-13",
        "jurisdiction": "European Union",
        "authority_level": "Binding Regulation",
    },
    {
        "source_id": "REG-GDPR-001",
        "title": "General Data Protection Regulation",
        "organization": "European Union",
        "source_type": "Law / Regulation",
        "url": "https://eur-lex.europa.eu/eli/reg/2016/679",
        "topic": "Data Protection",
        "summary": "Regulates processing of personal data. Requires lawful basis, data minimization, purpose limitation, and data protection impact assessments.",
        "publication_date": "2016-04-27",
        "jurisdiction": "European Union",
        "authority_level": "Binding Regulation",
    },
    {
        "source_id": "STD-NIST-AIRMF-001",
        "title": "NIST AI Risk Management Framework",
        "organization": "National Institute of Standards and Technology",
        "source_type": "Industry Standard / Framework",
        "url": "https://www.nist.gov/itl/ai-risk-management-framework",
        "topic": "AI Risk Management",
        "summary": "Voluntary framework for managing AI risks. Covers governance, mapping, measurement, and management of AI risks across the lifecycle.",
        "publication_date": "2023-01-18",
        "jurisdiction": "United States",
        "authority_level": "Voluntary Framework",
    },
    {
        "source_id": "STD-ISO42001-001",
        "title": "ISO/IEC 42001 - AI Management System",
        "organization": "International Organization for Standardization",
        "source_type": "Industry Standard / Framework",
        "url": "https://www.iso.org/standard/81230.html",
        "topic": "AI Management Systems",
        "summary": "International standard for AI management systems. Provides requirements for establishing, implementing, and maintaining AI governance.",
        "publication_date": "2023-12-01",
        "jurisdiction": "International",
        "authority_level": "International Standard",
    },
    {
        "source_id": "GUIDE-NIST-AI100-001",
        "title": "NIST AI 100-1: AI Accountability Framework",
        "organization": "National Institute of Standards and Technology",
        "source_type": "Regulatory Guidance",
        "url": "https://www.nist.gov/publications/ai-accountability-framework",
        "topic": "AI Accountability",
        "summary": "Framework for AI accountability practices. Covers governance, risk management, performance measurement, and stakeholder engagement.",
        "publication_date": "2024-05-01",
        "jurisdiction": "United States",
        "authority_level": "Government Guidance",
    },
    {
        "source_id": "GUIDE-EU-AIHLEG-001",
        "title": "EU AI Act High-Risk Guidelines",
        "organization": "European Commission",
        "source_type": "Regulatory Guidance",
        "url": "https://digital-strategy.ec.europa.eu/en",
        "topic": "High-Risk AI Systems",
        "summary": "Guidance on implementing high-risk AI system requirements. Explains conformity assessment, transparency, and human oversight obligations.",
        "publication_date": "2024-06-01",
        "jurisdiction": "European Union",
        "authority_level": "Regulatory Guidance",
    },
    {
        "source_id": "RES-MIT-ALGO-001",
        "title": "Algorithmic Accountability: Decision-Making, Data, and Automation",
        "organization": "MIT",
        "source_type": "Research",
        "url": "https://www.annualreviews.org/doi/10.1146/annurev-controls-061422-001633",
        "topic": "Algorithmic Fairness",
        "summary": "Research on fairness metrics, disparate impact, and bias detection in automated decision systems.",
        "publication_date": "2023-01-01",
        "jurisdiction": "Global",
        "authority_level": "Peer-Reviewed Research",
    },
    {
        "source_id": "RES-STANFORD-HAI-001",
        "title": "AI Index Report 2024",
        "organization": "Stanford University",
        "source_type": "Research",
        "url": "https://aiindex.stanford.edu/report/",
        "topic": "AI Trends and Risks",
        "summary": "Annual report on AI development, adoption, and governance trends. Covers technical capabilities, policy, and societal impacts.",
        "publication_date": "2024-04-15",
        "jurisdiction": "Global",
        "authority_level": "Research Institution",
    },
    {
        "source_id": "VENDOR-AWS-AI-001",
        "title": "AWS Responsible AI Guidelines",
        "organization": "Amazon Web Services",
        "source_type": "Vendor Information",
        "url": "https://aws.amazon.com/machine-learning/responsible-machine-learning/",
        "topic": "Responsible AI Practices",
        "summary": "AWS guidelines for responsible AI development and deployment. Covers fairness, explainability, privacy, and robustness.",
        "publication_date": "2024-01-01",
        "jurisdiction": "Global",
        "authority_level": "Vendor Documentation",
    },
    {
        "source_id": "VENDOR-GOOGLE-AI-001",
        "title": "Google AI Principles",
        "organization": "Google",
        "source_type": "Vendor Information",
        "url": "https://ai.google/responsibility/principles/",
        "topic": "AI Ethics Principles",
        "summary": "Google's principles for responsible AI development. Covers social benefit, bias, safety, accountability, and privacy.",
        "publication_date": "2023-01-01",
        "jurisdiction": "Global",
        "authority_level": "Vendor Documentation",
    },
    {
        "source_id": "WEB-AI-GOV-001",
        "title": "AI Governance Best Practices",
        "organization": "AI Governance Alliance",
        "source_type": "General Web Content",
        "url": "https://www.weforum.org/ai-governance",
        "topic": "AI Governance Practices",
        "summary": "Overview of AI governance best practices for organizations. Covers policy, risk management, and stakeholder engagement.",
        "publication_date": "2024-03-01",
        "jurisdiction": "Global",
        "authority_level": "Industry Initiative",
    },
    {
        "source_id": "REG-US-EO-AI-001",
        "title": "Executive Order on AI Safety",
        "organization": "White House",
        "source_type": "Law / Regulation",
        "url": "https://www.whitehouse.gov/briefing-room/presidential-actions/2023/10/30/executive-order-on-the-safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence/",
        "topic": "AI Safety Requirements",
        "summary": "US executive order establishing AI safety and security standards. Requires safety testing, privacy protections, and equity measures.",
        "publication_date": "2023-10-30",
        "jurisdiction": "United States",
        "authority_level": "Executive Order",
    },
]


SAMPLE_USE_CASES = [
    {
        "name": "AI Recruitment Screening",
        "industry": "Human Resources",
        "purpose": "Rank job applicants based on resumes and assessment results to identify top candidates for interviews",
        "ai_capability": "Resume screening and candidate ranking",
        "data_types": ["personal_data", "sensitive_data"],
        "decision_type": "decision_support",
        "human_oversight": "required",
        "model_type": "classification",
        "deployment_status": "Production",
        "affected_population": 5000,
    },
    {
        "name": "Bank Loan Risk Scoring",
        "industry": "Banking",
        "purpose": "Predict whether a loan applicant is likely to default based on financial history and credit data",
        "ai_capability": "Credit risk prediction",
        "data_types": ["personal_data", "financial_data", "sensitive_data"],
        "decision_type": "automated",
        "human_oversight": "optional",
        "model_type": "classification",
        "deployment_status": "Production",
        "affected_population": 25000,
    },
    {
        "name": "Customer Support AI",
        "industry": "Technology",
        "purpose": "Classify customer complaints and automatically prioritize them based on urgency and sentiment",
        "ai_capability": "Text classification and prioritization",
        "data_types": ["personal_data"],
        "decision_type": "advisory",
        "human_oversight": "required",
        "model_type": "generative_ai",
        "deployment_status": "Production",
        "affected_population": 100000,
    },
    {
        "name": "Healthcare Appointment Risk Prediction",
        "industry": "Healthcare",
        "purpose": "Predict patients who may miss appointments to enable proactive outreach and scheduling optimization",
        "ai_capability": "No-show prediction",
        "data_types": ["personal_data", "health_data", "sensitive_data"],
        "decision_type": "decision_support",
        "human_oversight": "required",
        "model_type": "classification",
        "deployment_status": "Pilot",
        "affected_population": 8000,
    },
]
